### ISSUE TITLE
Org Units - changing any permisson/role results in 500

### ISSUE THREAD

**Issue by brainthee** [brainthee/CHAOTICA#27]
Can't bump user permissions and modals don't seem to disappear when a button is pressed.

**Comment by brainthee** [comment]
Also - when trying to edit the org unit in Django admin, get the following exception "Permission.DoesNotExist" via Sentry: https://na-ofc.sentry.io/share/issue/0fe3398cba7b4164b09ed70db3ee1fa5/

**Comment by brainthee** [comment]
Looks like modals not going on the org page is the same issue!

```
[17/Jan/2024 16:02:01] "GET /autocomplete/users?q=adi HTTP/1.1" 200 110
'Add new perm: view_job'
Internal Server Error: /ops/unit/uki/members/add
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/chaotica/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/chaotica/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/projects/chaotica/app/jobtracker/views/orgunit.py", line 60, in organisationalunit_add
    membership.save()
  File "/home/adrian/projects/chaotica/app/jobtracker/models/orgunit.py", line 194, in save
    self.unit.syncPermissions()
  File "/home/adrian/projects/chaotica/app/jobtracker/models/orgunit.py", line 87, in syncPermissions
    assign_perm(new_perm, user, self)
  File "/home/adrian/.virtualenvs/chaotica/lib/python3.10/site-packages/guardian/shortcuts.py", line 131, in assign_perm
    return model.objects.assign_perm(perm, user, obj)
  File "/home/adrian/.virtualenvs/chaotica/lib/python3.10/site-packages/guardian/managers.py", line 39, in assign_perm
    permission = Permission.objects.get(content_type=ctype, codename=perm)
  File "/home/adrian/.virtualenvs/chaotica/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/chaotica/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Permission.DoesNotExist: Permission matching query does not exist.
```

**Comment by brainthee** [comment]
Ok this is linked to #13 as we need to rejig the permission model to be more sensible and intuitive.
